# Generated by Django 5.2b1 on 2025-03-30 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='UUID',
                    ),
                ),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('token_version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='UUID',
                    ),
                ),
                ('description', models.CharField(max_length=300)),
                (
                    'image_url',
                    models.URLField(blank=True, max_length=350, null=True),
                ),
                ('target', models.JSONField(default=dict)),
                ('max_count', models.IntegerField()),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_until', models.DateField(blank=True, null=True)),
                (
                    'mode',
                    models.CharField(
                        choices=[('COMMON', 'Common'), ('UNIQUE', 'Unique')],
                        max_length=10,
                    ),
                ),
                (
                    'promo_common',
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'company',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='business.company',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=30)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                (
                    'promo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='unique_codes',
                        to='business.promo',
                    ),
                ),
            ],
            options={
                'unique_together': {('promo', 'code')},
            },
        ),
    ]
