# Generated by Django 5.2b1 on 2025-03-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=300)),
                (
                    'image_url',
                    models.URLField(blank=True, max_length=350, null=True),
                ),
                ('target', models.JSONField(default=dict)),
                ('max_count', models.IntegerField()),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_until', models.DateField(blank=True, null=True)),
                (
                    'mode',
                    models.CharField(
                        choices=[('COMMON', 'Common'), ('UNIQUE', 'Unique')],
                        max_length=10,
                    ),
                ),
                (
                    'promo_common',
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'company',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='business.company',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=30)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                (
                    'promo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='unique_codes',
                        to='business.promo',
                    ),
                ),
            ],
            options={
                'unique_together': {('promo', 'code')},
            },
        ),
    ]
