# Generated by Django 5.2 on 2025-05-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="used_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="token_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="promo",
            name="max_count",
            field=models.PositiveIntegerField(),
        ),
    ]
