# Generated by Django 5.2 on 2025-05-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_promo_used_count_alter_company_token_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="like_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
