# Generated by Django 5.2 on 2025-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_promo_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="comment_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
