# === Promo ===
PROMO_MODE_COMMON = 'COMMON'
PROMO_MODE_UNIQUE = 'UNIQUE'
PROMO_MODE_CHOICES = [
    (PROMO_MODE_COMMON, 'Common'),
    (PROMO_MODE_UNIQUE, 'Unique'),
]


PROMO_DESC_MIN_LENGTH = 10
PROMO_DESC_MAX_LENGTH = 300
PROMO_IMAGE_URL_MAX_LENGTH = 350


# === Promo Common ===
PROMO_COMMON_CODE_MIN_LENGTH = 5
PROMO_COMMON_CODE_MAX_LENGTH = 30
PROMO_COMMON_MIN_COUNT = 1
PROMO_COMMON_MAX_COUNT = 100_000_000


# === Promo Unique ===
PROMO_UNIQUE_CODE_MIN_LENGTH = 3
PROMO_UNIQUE_CODE_MAX_LENGTH = 30
PROMO_UNIQUE_LIST_MIN_ITEMS = 1
PROMO_UNIQUE_LIST_MAX_ITEMS = 5000
PROMO_UNIQUE_MAX_COUNT = 1


# === Target ===
TARGET_AGE_MIN = 0
TARGET_AGE_MAX = 100
TARGET_COUNTRY_CODE_LENGTH = 2
TARGET_CATEGORY_MIN_LENGTH = 2
TARGET_CATEGORY_MAX_LENGTH = 20
TARGET_CATEGORY_MAX_ITEMS = 20
